# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-13 07:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=100, unique=True)),
                ('product_name', models.CharField(max_length=100)),
                ('product_desc', models.TextField(blank=True, null=True)),
                ('mrp', models.FloatField()),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'product_detail',
            },
        ),
    ]
