# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-14 05:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20171214_0513'),
    ]

    operations = [
        migrations.AddField(
            model_name='productrating',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
